# Generated by Django 5.1.3 on 2025-09-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
