# Generated by Django 5.1.3 on 2025-11-07 04:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_remove_car_assigned_to_car_for_sale_car_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
